ヘッダーとヒーローの作成
Ryoma0217/fronend-basic-site pull request #1
Opened 2024-04-25 13:30 UTC by Ryoma0217

2024-04-26 12:37 UTC, o-zack-0390 commented on index.html
> +            <span class="hero-main-copy-accent">"GRAND"</span>
「"」が Figma の手本と異なっています！

2024-04-26 12:49 UTC, o-zack-0390 requested changes
コメントしました✨
1点だけ確認お願いします！

2024-04-27 04:18 UTC, Ryoma0217 commented on index.html
> +            <span class="hero-main-copy-accent">"GRAND"</span>
修正しました。テキスト自体もコピーして貼り付けた方が間違いないですね。
今後第三、四部に進んでいく際はブランチを変更する必要はありますか。

2024-04-27 11:27 UTC, o-zack-0390 commented on index.html
> +            <span class="hero-main-copy-accent">"GRAND"</span>
>>>テキスト自体もコピーして貼り付けた方が間違いないですね。
スペルミスを減らせるので、コピペした方が良いと思います！

>>>今後第三、四部に進んでいく際はブランチを変更する必要はありますか。
ブランチを変更した方が良いと思います！
第3部、第4部 に分けて作業ブランチを作成した方が「部」ごとの編集内容が分かりやすくなり保守性が上がります。
また、単純に「部」ごとにブランチが分かれている方がレビュワー側がレビューしやすいです（）
そのため、第三部、第四部ともに main ブランチから作業ブランチを作成した方が良いのではと自分は思います！

2024-04-29 14:04 UTC, ssshun3 approved these changes
LGTM

2024-04-29 14:44 UTC, merged