AboutとCourseの作成
Ryoma0217/fronend-basic-site pull request #2
Opened 2024-05-04 03:17 UTC by Ryoma0217

2024-05-05 11:35 UTC, o-zack-0390 requested changes
コメントしました✨
２点確認お願いします！

2024-05-05 11:35 UTC, o-zack-0390 commented on style.css
> +  background: var(--color-background-black);
背景色が Figma のお手本と異なっています！

2024-05-05 11:35 UTC, o-zack-0390 commented on style.css
> +  gap: 10px;
course-body の gap がスマホ対応時にも適用されており、Figma のお手本と異なっています！

2024-05-08 04:46 UTC, Ryoma0217 commented on style.css
> +  gap: 10px;
修正しました。よろしくお願いいたします。

2024-05-10 12:32 UTC, ssshun3 reviewed
Coursesの説明部分に関して、hover時に黄色が若干変化するのでその修正をお願いします。
![image](https://github.com/Ryoma0217/fronend-basic-site/assets/110015394/cfd4079f-b8ff-4a43-82a6-d8cac0f1a6cb)

2024-05-11 04:04 UTC, ssshun3 approved these changes
LGTMです

2024-05-12 02:34 UTC, merged