Signupとfooterの作成
Ryoma0217/fronend-basic-site pull request #3
Opened 2024-05-13 08:26 UTC by Ryoma0217

2024-05-14 04:20 UTC, o-zack-0390 requested changes
コメントしました。
1点だけ確認お願いします！

2024-05-14 04:20 UTC, o-zack-0390 commented on style.css
> +  gap: 20px;
.signup-form で実装している一番下の gap がお手本(下図)と異なっています！

<img width="584" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/a754beb4-fe9b-4d3e-a1f7-5122172daf41">
<img width="584" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/8c80d677-9ef1-47f8-b877-257e2eb16c4c">

2024-05-15 06:00 UTC, Ryoma0217 commented on style.css
> +  gap: 20px;
コメントありがとうございます。修正しましたが、他にも修正できる箇所あったらお願いします。
検証ツールを見た所、display:grid;やrow-gap:40pxを使っていたのですが、自分はfigmaを見ながらpaddingやgapを使って実装しました。自分のやり方でも大丈夫でしょうか。

2024-05-16 03:52 UTC, o-zack-0390 commented on style.css
> +  gap: 20px;
フォームの箇所ですが、flex でも問題ないです！

というのも、grid でできることの殆どは flex でも同じことができるからです。
自分が参加したインターンシップの中には、共通ルールとしてレイアウトの調整は flex で統一させ、可読性を向上させる方針をとっているとこもありました。( バックエンド側を担当してたので話を聞いただけなのですが . . . )

しかし、flex だけだと回りくどいコードになってしまうことが多いなと個人的には思っているので、自分は必要に応じて両方とも使うようにしています！

そのため、ここら辺のやり方は人によって違いがあり、どれも間違いとはいえない気がするため、 Ryoma さんのやり方でも全然大丈夫だと思います！


あくまで僕個人の考えです！ 間違っているかもしれないので参考程度にしておいてください！

2024-05-16 03:53 UTC, o-zack-0390 commented on style.css
> +  gap: 20px;
**フォームの修正について**

自分なら CSSの signup-form, signup-input-wrapperの内容を全て削除し、以下の手順で grid に変えると思います。

1. signup-input-wrapper に grid を設定.

2. htmlの<div class="signup-input-wrapper">が複数存在するため一つに集約し、子要素にinput要素を全て配置.

3. signup-form に grid を設定.

signup-input-wrapper と signup-form に grid を設定して gird の入れ子状態をわざわざ作るのには gap の関係で都合が良いからです。gird の細かい設定はレイアウトを見ながら調整してみてください！

2024-05-16 04:07 UTC, o-zack-0390 reviewed
**レイアウトの修正(任意)**

非常に細かいところですがお手本と異なっている箇所を記載しました！
可能であれば修正した方が良さそうです！

2024-05-16 04:07 UTC, o-zack-0390 commented on index.html
> +            <input
細かい箇所で見るとinputのサイズがお手本(下図)と微妙に異なっていますが、ここに関しては  Figma に明確な判断基準が記載されていないため、問題ないと思っています。

<img width="598" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/38bde448-6344-4cef-bc94-c60af5fcbba0">


<img width="598" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/79101dfa-2012-41d2-8db8-300e9fa04187">

2024-05-16 04:07 UTC, o-zack-0390 commented on index.html
> +      <div class="footer-copyright">©2023 GrandPlayers</div>
お手本では @ と 2023 の間にスペースがあります！
変えなくても問題はなさそうですが、なるべくお手本と同じレイアウトにした方が良いと思うので変更した方が良さそうです！

2024-05-16 04:17 UTC, o-zack-0390 requested changes
コメントしました！
p タグの margin の問題は修正をお願いします！

2024-05-16 04:17 UTC, o-zack-0390 commented on index.html
> +        <p class="signup-text">Grand Playersでは、ご利用登録いただけた方に対し、３レッスン分の無料枠をプレゼントいたします！
margin が入っており、お手本(下図)と異なっています！
p タグはデフォルトで margin が設定されているため削除しましょう！

<img width="583" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/3b39e26a-3eaa-4f83-a82c-54d163ef7198">

<img width="583" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/ce45a84a-1084-46d8-882b-f0066f71fecf">

2024-05-16 04:36 UTC, o-zack-0390 reviewed
**HTMLコードの修正(任意)**

HTML に関しても修正の余地がありそうなので記載しました！
ただし、恐らく課題の範囲を超えてそうなので修正しなくても問題ないと思います！

2024-05-16 04:36 UTC, o-zack-0390 commented on index.html
> +                  id="ギター歴 (年)"
それぞれのinput要素の id は、対応するlabel要素の for 属性と同じにする必要があります！
→ 正確にはフォームの自動入力(autocompleteといいます)やアクセシビリティが機能しなくなりエラーが出力されます！

<img width="1331" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/97927267-8d5d-44cb-a565-ca69260fcf90">

2024-05-16 04:36 UTC, o-zack-0390 commented on index.html
> +                  id="ギター歴 (年)"
同じくそれぞれのinput要素にautocompleteにかんする警告があります！
→ 自動入力に関する項目なので、適用しなくてもよいと思います！一応 autocomplete="off" に設定することで警告は消えます.

<img width="1330" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/9252a1e8-ae4c-486f-a0cd-a99d9aff560e">

2024-05-16 05:22 UTC, o-zack-0390 commented on index.html
> +            <input
お手本(下図)だと Footer の @ と 2023 の間にスペースがあります！

<img width="713" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/fc4158f6-85c1-454f-bdd1-c490d42baafd">

<img width="643" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/b2820d31-5e6d-45f2-aeb1-bc955f39d11e">

2024-05-19 04:14 UTC, Ryoma0217 commented on style.css
> +  gap: 20px;
アドバイスいただき、ありがとうございます。非常に参考になります。検証ツールで試してみます。今回の修正については一旦そのままにさせてください。

2024-05-19 04:40 UTC, Ryoma0217 commented on index.html
> +            <input
footerのcopyrightのスペースを空けるよう修正しました。

2024-05-19 05:26 UTC, Ryoma0217 commented on index.html
> +        <p class="signup-text">Grand Playersでは、ご利用登録いただけた方に対し、３レッスン分の無料枠をプレゼントいたします！
marginのデフォルト設定に気づきませんでした。ありがとうございます。修正しました。

2024-05-19 05:59 UTC, Ryoma0217 commented on index.html
> +                  id="ギター歴 (年)"
autocomplete属性を追加しました。自動入力に関しては疑問に思っていたので理解が深まりました。いちお修正したので確認お願いします。

2024-05-20 13:59 UTC, o-zack-0390 requested changes
コメントしました！

1箇所だけスマホ画面での gap が異なっているとこがありました。
それ以外は特に問題ないように見えます！

issue も無くなっており、全体的にかなり良いと思います！

2024-05-20 13:59 UTC, o-zack-0390 commented on style.css
> +  margin-top: 20px;
申し訳ないです自分の方で見落としていました🙇‍♂️

スマホ画面だとここの gap が合計で 30px なのでお手本(右図)の 40px と異なっています。
デスクトップ画面では 40px になっているため、スマホ画面での margin-top を media screen で設定すれば直ると思います！

<img width="223" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/bce05b02-ed8a-48b1-96d5-8b7ad0347a3a">

<img width="364" alt="image" src="https://github.com/Ryoma0217/fronend-basic-site/assets/116938721/3eb3a020-2310-4273-a4af-88a92ebf7450">

2024-05-20 16:15 UTC, Ryoma0217 commented on style.css
> +  margin-top: 20px;
コメントありがとうございます。自分はgapを10pxに設定していたので、gapの合計を40pxにするためにボタンのmargin-topを30pxにしました。確認お願いします。

2024-05-22 16:38 UTC, ssshun3 reviewed
LGTMです。JS課題頑張って下さい！

2024-05-22 16:38 UTC, ssshun3 commented on index.html
> +                  name="guita-experience"
修正不要です。おそらくタイポですかね。
```suggestion
                  name="guitar-experience" 

```

2024-05-22 16:39 UTC, ssshun3 approved these changes

2024-05-23 15:21 UTC, merged